sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vaibhavsanil/docker-react:latest -f Dockerfile.dev .
script:
  - docker run -e CI=true vaibhavsanil/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-219866062071"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key:
  secure: $AWS_SECRET_KEY
