sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vaibhavsanil/docker-react:latest -f Dockerfile.dev .
script:
  - docker run -e CI=true vaibhavsanil/docker-react npm run test
