FROM node:15-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'

COPY --chown=node:node ./package.json ./

# RUN npm cache clean --force
#RUN npm config set registry="http://registry.npmjs.org/"
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm","run","start"]

